# This workflow will build and then publish a package to npm registry using yarn when a release is created

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@thegoodcompany'
      - run: yarn
      - run: yarn publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
